notifications:
  email:
  - cf-lamb@pivotallabs.com

language: go

go:
- 1.4
- tip

matrix:
  allow_failures:
    - go: tip

before_install:
- go get golang.org/x/tools/cmd/cover golang.org/x/tools/cmd/vet
- go get -v github.com/mattn/goveralls
- go install -v github.com/onsi/ginkgo/ginkgo

script: "PATH=$HOME/gopath/bin:$PATH ginkgo -r"

after_success:
- 'echo "mode: set" > all.coverprofile'
- 'find . -name "*.coverprofile" -exec grep -v mode: {} >> all.coverprofile \;'
- $WORK_DIR/bin/goveralls -coverprofile=all.coverprofile -repotoken=$COVERALLS_TOKEN
